# Generated by Django 2.2 on 2022-01-11 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220108_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='avalable',
            new_name='available',
        ),
    ]
