# Generated by Django 2.2 on 2022-01-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
